# Generated by Django 3.1.3 on 2020-11-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.CharField(max_length=100)),
                ('emotions', models.CharField(max_length=100)),
                ('body_reaction', models.CharField(max_length=100)),
                ('thoughts', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=100)),
            ],
        ),
    ]
