# Generated by Django 2.2.12 on 2020-12-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('current_weather', models.FloatField(default=1)),
                ('event', models.CharField(max_length=100)),
                ('emotions', models.CharField(max_length=100)),
                ('emotions_degree', models.CharField(max_length=100)),
                ('body_reaction', models.CharField(max_length=100)),
                ('thoughts', models.CharField(max_length=100)),
                ('outcome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EmotionsAvgTemperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('joyfullness', models.FloatField(blank=True, null=True)),
                ('average_temperature', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
