# Generated by Django 2.2.12 on 2020-12-10 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_stocks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stocks',
            new_name='Stocks1',
        ),
    ]
