# Generated by Django 3.1.3 on 2020-11-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0003_auto_20201130_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotions',
            name='emotions',
            field=models.CharField(max_length=100),
        ),
    ]
