# Generated by Django 3.1.3 on 2020-12-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_auto_20201130_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotions',
            name='emotions_degree',
            field=models.CharField(default='some text', max_length=100),
        ),
        migrations.AlterField(
            model_name='emotions',
            name='emotions',
            field=models.CharField(max_length=100),
        ),
    ]
