# Generated by Django 3.1.3 on 2020-12-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20201201_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.DecimalField(decimal_places=4, max_digits=11)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='emotions',
            name='emotions_degree',
            field=models.CharField(max_length=100),
        ),
    ]
