# Generated by Django 2.2.12 on 2020-12-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20201204_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotions',
            name='emotions_degree',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='emotions',
            name='currentweather',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='emotions',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
