# Generated by Django 2.2.12 on 2020-12-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20201204_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emotions',
            old_name='currentweather',
            new_name='current_weather',
        ),
        migrations.AlterField(
            model_name='emotions',
            name='emotions_degree',
            field=models.CharField(max_length=100),
        ),
    ]
