# Generated by Django 3.1.3 on 2020-12-02 18:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20201202_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 2, 18, 43, 4, 12892, tzinfo=utc)),
        ),
    ]
