# Generated by Django 2.2.12 on 2020-12-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20201202_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotions',
            name='currentweather',
            field=models.IntegerField(default=-0.61),
        ),
        migrations.AlterField(
            model_name='emotions',
            name='date',
            field=models.DateTimeField(default='2020-12-04 13:39:46'),
        ),
    ]
