# Generated by Django 2.2.12 on 2020-12-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_auto_20201204_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotions',
            name='currentweather',
            field=models.IntegerField(default=1.0),
        ),
        migrations.AlterField(
            model_name='emotions',
            name='date',
            field=models.DateTimeField(default='2020-12-04 16:57:13'),
        ),
    ]
